# Generated by Django 6.0.2 on 2026-02-21 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_tracker', '0018_consumptioncategory_has_student_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryStudentCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_count', models.IntegerField()),
                ('second_count', models.IntegerField(blank=True, default=0, null=True)),
                ('effective_date', models.DateField()),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_counts', to='water_tracker.consumptioncategory')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'category_student_counts',
                'ordering': ['-effective_date', '-entered_at'],
            },
        ),
    ]
