# Generated by Django 6.0.2 on 2026-02-21 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_tracker', '0019_categorystudentcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumptioncategory',
            name='student_count',
        ),
    ]
