# Generated by Django 6.0.2 on 2026-02-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_tracker', '0020_remove_student_count_from_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorystudentcount',
            name='display_count',
            field=models.CharField(choices=[('first', 'First Count (student_count)'), ('second', 'Second Count (second_count)')], default='first', max_length=10),
        ),
    ]
