# Generated by Django 6.0.2 on 2026-02-21 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_tracker', '0021_add_display_count_to_student_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumptioncategory',
            name='exclude_value',
        ),
        migrations.RemoveField(
            model_name='consumptioncategory',
            name='second_count',
        ),
    ]
