# Generated by Django 6.0.2 on 2026-02-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_tracker', '0022_remove_category_exclude_second_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_date', models.DateField(blank=True, null=True)),
                ('pr_no', models.CharField(blank=True, default='', max_length=100)),
                ('block_details', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('vendor', models.CharField(blank=True, default='', max_length=200)),
                ('bill_no', models.CharField(blank=True, default='', max_length=100)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('po_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('opex_date', models.DateField(blank=True, null=True)),
                ('opex_no', models.CharField(blank=True, default='', max_length=100)),
                ('opex_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('process', 'In Process')], default='process', max_length=10)),
                ('for_month', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'procurement_entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
