# Generated by Django 6.0.2 on 2026-02-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_tracker', '0023_add_procurement_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='procuremententry',
            name='po_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
