# Generated by Django 6.0.2 on 2026-02-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_tracker', '0024_add_po_no_to_procurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetApproved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('for_month', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'budget_approved',
                'ordering': ['-for_month'],
                'unique_together': {('for_month',)},
            },
        ),
    ]
