# Generated by Django 6.0.2 on 2026-02-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_tracker', '0026_passwordresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_master_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_operations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_reports',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_users',
            field=models.BooleanField(default=False),
        ),
    ]
