# Generated by Django 6.0.2 on 2026-03-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_tracker', '0027_user_can_access_master_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumptionentry',
            name='consumption_liters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='consumptionentry',
            name='current_reading',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='consumptionentry',
            name='previous_reading',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='waterentry',
            name='meter_reading_current',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='waterentry',
            name='meter_reading_previous',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='yieldentry',
            name='current_reading',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='yieldentry',
            name='previous_reading',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='yieldentry',
            name='yield_liters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
